# -*- coding: utf-8 -*-
"""PyPoll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18J7j4xrlE3aveoc--2YUA1UKmUFTW58z

Module 3 Challange - PyPoll

Import required python packages

PyPoll Data - Election Data
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

# Load the dataset
df_election = pd.read_csv('election_data.csv')
df_election.head()

# Analysis

total_votes = len(df_election)
total_votes

# Get the vote counts for each candidate
vote_counts = df_election['Candidate'].value_counts()
vote_counts

# Calculate percentages and format results
results = []
for candidate, votes in vote_counts.items():
    percentage = (votes / total_votes) * 100
    results.append(f"{candidate}: {percentage:.3f}% ({votes})")

# Determine the winner
winner = vote_counts.idxmax()
winner

# Print the election results
print("Election Results")
print("-------------------------")
print(f"Total Votes: {total_votes}")
print("-------------------------")

# Print out each candidate's name, vote count, and percentage of votes
for candidate, votes in vote_counts.items():
    percentage = (votes / total_votes) * 100
    print(f"{candidate}: {percentage:.3f}% ({votes})")

print("-------------------------")
print(f"Winner: {winner}")
print("-------------------------")

# Define the election results text
election_results_text = (
    "Election Results\n"
    "-------------------------\n"
    f"Total Votes: {total_votes}\n"
    "-------------------------\n"
)
for candidate, votes in vote_counts.items():
    percentage = (votes / total_votes) * 100
    election_results_text += f"{candidate}: {percentage:.3f}% ({votes})\n"
election_results_text += (
    "-------------------------\n"
    f"Winner: {winner}\n"
    "-------------------------\n"
)

# Print the election results to the terminal
print(election_results_text)

# Save the election results to a text file
election_filename = 'election_results.txt'
with open(election_filename, 'w') as text_file:
    text_file.write(election_results_text)

# Download the file to your local system
from google.colab import files
files.download(election_filename)  # Make sure the filename matches

