# -*- coding: utf-8 -*-
"""PyBank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MTVczhuno7L7MgFEZw3P8u42LAsxUBl

Module 3 Challange - PyBank

Import required python packages

PyBank Data - Budget Data
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

# Load the dataset
df_budget = pd.read_csv('budget_data.csv')
df_budget.head()

# Calculate the total number of months
total_months = len(df_budget)
total_months

# Calculate the net total amount of "Profit/Losses" over the entire period
total_profit_losses = df_budget['Profit/Losses'].sum()
total_profit_losses

# Calculate changes in "Profit/Losses" over the entire period
df_budget['Change'] = df_budget['Profit/Losses'].diff()

# Calculate the average of those changes
average_change = df_budget['Change'].mean()
average_change

# Find the greatest increase in profits
greatest_increase = df_budget['Change'].max()
greatest_increase_date = df_budget.loc[df_budget['Change'] == greatest_increase, 'Date'].iloc[0]

# Find the greatest decrease in profits
greatest_decrease = df_budget['Change'].min()
greatest_decrease_date = df_budget.loc[df_budget['Change'] == greatest_decrease, 'Date'].iloc[0]

# Print the analysis
print("Financial Analysis")
print("----------------------------")
print(f"Total Months: {total_months}")
print(f"Total: ${total_profit_losses}")
print(f"Average Change: ${average_change:.2f}")
print(f"Greatest Increase in Profits: {greatest_increase_date} (${int(greatest_increase)})")
print(f"Greatest Decrease in Profits: {greatest_decrease_date} (${int(greatest_decrease)})")

# Define the analysis_text variable with your analysis
analysis_text = (
    f"Financial Analysis\n"
    f"----------------------------\n"
    f"Total Months: {total_months}\n"
    f"Total: ${total_profit_losses}\n"
    f"Average Change: ${average_change:.2f}\n"
    f"Greatest Increase in Profits: {greatest_increase_date} (${int(greatest_increase)})\n"
    f"Greatest Decrease in Profits: {greatest_decrease_date} (${int(greatest_decrease)})\n"
)

# Print the analysis to the terminal
print(analysis_text)

# Save the results to a text file
with open('financial_analysis.txt', 'w') as text_file:
    text_file.write(analysis_text)

# Make sure the filename matches what you've saved
from google.colab import files
files.download('financial_analysis.txt')

